// ══════════════════════════════════════════════════════════════════
// ID SCHEME:  DXXX  where D = domain prefix, XXX = sequential
//
//   1XXX = General Security Concepts
//   2XXX = Threats, Vulnerabilities & Mitigations
//   3XXX = Security Architecture
//   4XXX = Security Operations
//   5XXX = Security Program Management & Oversight
//
// IDs are assigned sequentially within each domain across ALL arrays.
// IDs must be globally unique — ALL_Q merges all arrays at runtime.
//
// When adding a new question, pick the next unused number in its domain range.
// Next available: General 1033 | Threats 2081 | Arch 3013 | Ops 4029 | Gov 5024
//
// RULES:
//   1. The correct answer is ALWAYS choices[0] for MC, bank[0] for FITB,
//      redFlags[0] for Phish. Runtime shuffles — never rely on display order.
//   2. Every question must have: id, domain, q, exp + type-specific fields.
//
// QUESTION TEMPLATES:
//
// MC:   {id:XXXX, domain:'general', q:'Question?',
//         choices:['Correct','Wrong A','Wrong B','Wrong C'], exp:'...'},
//
// FITB: {id:XXXX, domain:'general', type:'fitb', q:'Sentence with ___ blank.',
//         answer:'correct', bank:['correct','wrong1','wrong2','wrong3'], exp:'...'},
//
// Match:{id:XXXX, domain:'general', type:'match', q:'Match X to Y.',
//         pairs:[{left:'Term',right:'Def'}, ...],  // 4 pairs
//         exp:'...'},
//
// Sort: {id:XXXX, domain:'operations', type:'sort', q:'Order these steps.',
//         steps:['Step 1','Step 2',...],  // steps[0] = correct first step
//         exp:'...'},
//
// T/F:  {id:XXXX, domain:'general', type:'tf', q:'True statement.', correct:true, exp:'...'},
//       {id:XXXX, domain:'general', type:'tf', q:'False statement.', correct:false,
//         wrongParts:['Incorrect claim','Correct claim','Alt 3','Alt 4'],
//         wrongAnswer:1,  // index of correct claim in wrongParts
//         exp:'...'},
//
// Phish:{id:XXXX, domain:'threats', type:'phish',
//         email:{from:'', to:'', subject:'', body:`...`},
//         redFlags:['Primary flag','Flag 2','Flag 3','Flag 4'],
//         correct:0,  // always 0
//         exp:'...'},
// ══════════════════════════════════════════════════════════════════

// DONE: Study Guide Chapters 1–5
const QUESTIONS=[
  // ── DOMAIN 1: GENERAL SECURITY CONCEPTS ──
  // ── STUDY GUIDE ──
  {id:1001,domain:'general',q:'Matt is updating the organization\'s threat assessment process. What category of control is Matt implementing?',choices:['Managerial','Operational','Technical','Corrective'],exp:'Managerial controls are procedural mechanisms that focus on the mechanics of the risk management process. Threat assessment is one example.'},
  {id:1002,domain:'general',q:'Chris is responding to a security incident that compromised one of his organization\'s web servers. He believes that the attackers defaced one or more pages on the website. What cybersecurity objective did this attack violate?',choices:['Integrity','Confidentiality','Nonrepudiation','Availability'],exp:'The defacement of a website alters content without authorization and is, therefore, a violation of the integrity objective. The attackers may also have breached the confidentiality or availability of the website, but the scenario does not provide us with enough information to draw those conclusions.'},
  {id:1003,domain:'general',q:'Tonya is concerned about the risk that an attacker will attempt to gain access to her organization\'s database server. She is searching for a control that would discourage the attacker from attempting to gain access. What type of security control is she seeking to implement?',choices:['Deterrent','Preventative','Detective','Corrective'],exp:'Deterrent controls are designed to prevent an attacker from attempting to violate security policies in the first place.'},
  {id:1004,domain:'general',q:'Tina is tuning her organization\'s intrusion prevention system to prevent false positive alerts. What type of control is Tina implementing?',choices:['Technical control','Physical control','Managerial control','Operational control'],exp:'Technical controls enforce CIA in the digital space. Examples include firewall rules, access control lists, intrusion prevention systems, and encryption.'},
  {id:1005,domain:'general',q:'Which one of the following is not a common goal of a cybersecurity attacker?',choices:['Allocation','Disclosure','Denial','Alteration'],exp:'The three primary goals of cybersecurity attackers are disclosure, alteration, and denial. These map directly to the three objectives of cybersecurity professionals: confidentiality, integrity, and availability.'},
  {id:1006,domain:'general',q:'Which one of the following data elements is not commonly associated with identity theft?',choices:['Frequent flyer number','Social Security number','Driver\'s license number','Passport number'],exp:'Although it is possible that a frequent flyer account number, or any other account number for that matter, could be used in identity theft, it is far more likely that identity thieves would use core identity documents.'},
  {id:1007,domain:'general',q:'What term best describes an organization\'s desired security state?',choices:['Control objectives','Security priorities','Strategic goals','Best practices'],exp:'As an organization analyzes its risk environment, technical and business leaders determine the level of protection required to preserve the confidentiality, integrity, and availability of their information and systems. They express this requirements by writing the control objectives that the organization wishes to achieve.'},
  {id:1008,domain:'general',q:'Jeff is concerned about the effects that a ransomware attack might have on his organization and is designing a backup methodology that would allow the organization to quickly restore data after such an attack. What type of control is Jeff implementing?',choices:['Corrective','Preventative','Detective','Deterrent'],exp:'Corrective controls remediate security issues that have already occurred. Restoring backups after a ransomware attack is an example of a corrective control.'},
  {id:1009,domain:'general',q:'Lou mounted a "Beware of Dog" sign on the fence surrounding his organization\'s datacenter. What control type BEST describes this control?',choices:['Deterrent','Compensating','Detective','Physical'],exp:'This question is a little tricky. The use of an actual guard dog could be considered a deterrent, physical, or detective control. It could even be a compensating control in some circumstances. However, the question asks about the presence of a sign and does not state that an actual dog is used. The sign only has value as a deterrent control.'},
  {id:1010,domain:'general',q:'What technology uses mathematical algorithms to render information unreadable to those lacking the required key?',choices:['Data encryption','Data loss prevention','Data obfuscation','Data minimization'],exp:'Encryption uses mathematical algorithms to protect information in transit and at rest. Without the decryption key, the data is unintelligible.'},
  {id:1011,domain:'general',q:'Greg recently conducted an assessment of his organization\'s security controls and discovered a potential gap: the organization does not use full-disk encryption on laptops. What type of control gap exists in this case?',choices:['Preventative','Detective','Deterrent','Corrective'],exp:'The use of full-disk encryption is intended to prevent a security incident from occurring if a device is lost or stolen. Therefore, this is a preventative control gap.'},
  {id:1012,domain:'general',q:'Nolan is writing an after-action report on a breach where attackers stole thousands of customer records. What cybersecurity principle was most impacted?',choices:['Confidentiality','Availability','Nonrepudiation','Integrity'],exp:'The disclosure of sensitive information to unauthorized individuals is a violation of the principle of confidentiality.'},
  {id:1013,domain:'general',q:'Which one of the following objectives is NOT one of the three main objectives of information security?',choices:['Nonrepudiation','Integrity','Availability','Confidentiality'],exp:'The three primary objectives are confidentiality, integrity, and availability (CIA). Nonrepudiation is important but not part of the core CIA triad.'},
  {id:1014,domain:'general',q:'Which one of the following data protection techniques is reversible when conducted properly?',choices:['Tokenization','Masking','Hashing','Shredding'],exp:'Tokenization uses a lookup table and is designed to be reversible. Hashing is one-way and shredding is permanent.'},
  {id:1015,domain:'general',q:'Which one of the following statements is NOT true about compensating controls under PCI DSS?',choices:['Controls used to fulfill one PCI DSS requirement may be used to compensate for the absence of a control needed to meet another requirement.','Controls must meet the intent of the original requirement.','Controls must meet the rigor of the original requirement.','Compensating controls must provide a similar level of defense as the original requirement.'],exp:'PCI DSS compensating controls must be "above and beyond" other PCI DSS requirements. This specifically bans the use of a control used to meet one requirement as a compensating control for another requirement.'},
  // ── PRACTICE TESTS ──
  {id:1016,domain:'general',q:'Felicia wants to deploy an encryption solution that will protect files in motion as they are copied between file shares as well as at rest, and also needs it to support granular, per user security. What type of solution should she select?',choices:['File encryption','Partition encryption','Full-disk encryption','Record-level encryption'],exp:'File encryption meets all of the needs described.'},
  {id:1017,domain:'general',q:'Valerie wants to use a certificate to handle multiple subdomains for her website, including the sales.example.com and support.example.com subdomains. What type of certificate should she use?',choices:['A wildcard certificate','A self-signed certificate','A root of trust certificate','A domain validation certificate'],exp:'Wildcard certificates are used to handle multiple subdomains with a single certificate.'},
  {id:1018,domain:'general',q:'What information is analyzed during a gap analysis?',choices:['Control objectives and controls intended to meet the objectives','Physically separate networks and their potential connection points','Compensating controls and the controls they are replacing','Security procedures and the policies they are designed to support'],exp:'Gap analysis considers control objectives and the controls that are intended to meet the objectives.'},
  {id:1019,domain:'general',q:'Susan\'s team has recommended an application restart for a production, customer-facing application as part of an urgent patch due to a security update. What technical implication is the most common concern when conducting an application restart?',choices:['The downtime during the restart','Application configuration changes caused by the restart','Whether the patch will properly apply','Lack of security controls during the restart'],exp:'In most production environments downtime is the primary concern when considering an application restart. Many application architectures are designed to allow restarts of individual systems or services without creating an outage or downtime.'},

  // ── DOMAIN 2: THREATS, VULNERABILITIES, & MITIGATIONS ──
  // ── STUDY GUIDE ──
  {id:2001,domain:'threats',q:'Derek\'s organization is worried about a disgruntled employee publishing sensitive business information. What type of threat should Derek work to protect against?',choices:['Insider threats','Shoulder surfing','Social engineering','Phishing'],exp:'Derek\'s organization is worried about insider threats, or threats that are created by employees and others who are part of the organization or are otherwise trusted by the organization.'},
  {id:2002,domain:'threats',q:'Wendy is scanning cloud-based repositories for sensitive information. Which one should concern her most if discovered in a public repository?',choices:['API keys','Product manuals','Source code','Open source data'],exp:'API keys should NEVER be in public repositories because they may grant unauthorized individuals access to systems and data.'},
  {id:2003,domain:'threats',q:'Which one of the following motivations is most commonly attributed to hacktivists?',choices:['Political/philosophical beliefs','War','Financial gain','Ethical'],exp:'Hacktivists are defined by advancing their political or philosophical beliefs through cyberattacks.'},
  {id:2004,domain:'threats',q:'Kolin is a penetration tester hired by a healthcare system to conduct a penetration test. What term best describes Kolin\'s work?',choices:['Authorized attacker','Unauthorized attacker','Unknown attacker','Semi-authorized attacker'],exp:'Attacks conducted as part of an authorized penetration test are white-hat hacking attacks, regardless of whether done internally or by an external firm.'},
  {id:2005,domain:'threats',q:'Which one of the following attackers is most likely to be associated with an APT?',choices:['Nation-state actor','Hacktivist','Unskilled','Insider'],exp:'Advanced persistent threats (APTs) are most commonly associated with nation-state actors.'},
  {id:2006,domain:'threats',q:'Which of the following threat actors typically has the greatest access to resources?',choices:['Nation-state actors','Organized crime','Hacktivists','Insider threats'],exp:'Nation-state actors are government sponsored, and they typically have the greatest access to resources, including tools, money, and talent.'},
  {id:2007,domain:'threats',q:'Of common threat vectors, which one is most commonly exploited by remote attackers?',choices:['Email','Direct access','Wireless','Removable media'],exp:'Email is the most common threat vector exploited by remote attackers using phishing. The other vectors require physical proximity.'},
  {id:2008,domain:'threats',q:'Which one of the following is the best example of a hacktivist group?',choices:['Anonymous','Chinese military','U.S. government','Russian mafia'],exp:'The Chinese military and U.S. government are nation-state APTs. Russian mafia is organized crime. Anonymous is the world\'s most prominent hacktivist group.'},
  {id:2009,domain:'threats',q:'What type of assessment is particularly useful for identifying insider threats?',choices:['Behavioral','Instinctual','Habitual','IoC-based'],exp:'Behavioral assessments identify insider threats by examining context — after-hours logins, misuse of credentials, abnormal access patterns.'},
  {id:2010,domain:'threats',q:'Cindy is concerned that her organization may be targeted by a supply chain attack and is conducting a review of all of her vendor and supplier partners. Which one of the following organizations is least likely to be the conduit for a supply chain attack?',choices:['Talent provider','Hardware provider','Software provider','Managed service provider'],exp:'Supply chain attacks are typically associated with vendors and suppliers that provide technology infrastructure or services that may be compromised. This would include hardware and software providers as well as managed service providers (MSPs). Talent providers, who help with staffing solutions, are generally not considered common avenues for supply chain attacks.'},
  {id:2011,domain:'threats',q:'Greg believes that an attacker may have installed malicious firmware in a network device before it was delivered to his organization by the supplier. What type of threat vector best describes this attack?',choices:['Supply chain','Removable media','Cloud','Direct access'],exp:'Tampering with equipment before it reaches the intended user is a supply chain threat. It is also possible to describe this attack as a direct access attack because it involved physical access to the device, but supply chain is a more relevant answer.'},
  {id:2012,domain:'threats',q:'Vince recently received the hash values of malicious software that several other firms in his industry found installed on their systems after a compromise. What term best describes this information?',choices:['IoC','Vulnerability feed','TTP','RFC'],exp:'Specific details of attacks used to identify compromises are indicators of compromise (IoCs). This data may also be described as an adversary tactics, techniques, and procedures (TTP), but the fact that it is a set of file signatures makes it more closely match the definition of an IoC.'},
  {id:2013,domain:'threats',q:'Ursula discovered that developers are using an unsanctioned cloud messaging tool. What term best describes this?',choices:['Shadow IT','System integration','Vendor management','Data exfiltration'],exp:'Using unapproved technology for business purposes is the classic definition of shadow IT.'},
  {id:2014,domain:'threats',q:'Tom\'s organization recently learned that the vendor is discontinuing support for their customer relationship management (CRM) system. What should concern Tom the most from a security perspective?',choices:['Unavailability of future patches','Lack of technical support','Theft of customer information','Increased costs'],exp:'Tom\'s greatest concern should be that running unsupported software exposes his organization to the risk of new, unpatchable vulnerabilities.'},
  {id:2015,domain:'threats',q:'Edward Snowden, a government contractor, disclosed sensitive documents to journalists. Which term best describes Snowden\'s activities?',choices:['Insider','State actor','APT','Organized crime'],exp:'Snowden had authorized access and exploited it to make an unauthorized disclosure — the definition of an insider threat.'},
  {id:2016,domain:'threats',q:'Which of the following is NOT likely to be a useful IoC for a rootkit?',choices:['Pop-ups demanding a ransom','File hashes','Command and control domains','Behavior-based identifiers'],exp:'Rootkits are designed to be stealthy — ransomware pop-ups work against that. File hashes, C2 details, and behavioral identifiers are useful rootkit IoCs.'},
  {id:2017,domain:'threats',q:'A staff member\'s credentials were used to change student grades. The staff member denies doing it. Which malware is most likely responsible?',choices:['A keylogger','A rootkit','Spyware','A logic bomb'],exp:'A keylogger captures credentials. A student could then use those credentials to make unauthorized changes.'},
  {id:2018,domain:'threats',q:'Amanda notices traffic between her systems and a known malicious host on TCP port 6667. What is she most likely detecting?',choices:['Command and control','Spyware','A worm','A hijacked web browser'],exp:'Amanda has most likely discovered a botnet\'s command and control channel, and the system or systems she is monitoring are probably using IRC as the command and control channel. Spyware typically uses HTTP/HTTPS.'},
  {id:2019,domain:'threats',q:'Mike discovers software on a company computer that allows attackers remote access to systems. How should he classify this?',choices:['A backdoor','A worm','Crypto malware','A Trojan'],exp:'Remote access to a system is provided by a backdoor. Backdoors may appear in firmware or hardware too.'},
  {id:2020,domain:'threats',q:'Ryan wants to prevent logic bombs created by insider threats from impacting his organization. What technique will most effectively limit the likelihood of logic bombs being put in place?',choices:['Using a code review process','Deploying antivirus software','Deploying endpoint detection and response (EDR) software','Disabling autorun for USB drives'],exp:'Logic bombs are embedded in code, so Ryan\'s organization would get the most benefit from a code review process for any code that goes into production.'},
  {id:2021,domain:'threats',q:'What is the primary impact of bloatware?',choices:['Consuming resources','Logging keystrokes','Providing information about users and devices to third parties','Allowing unauthorized remote access'],exp:'Bloatware is typically not a significant security threat, but it consumes resources like disk space, CPU, and memory. Unfortunately, some bloatware can be vulnerable and may not get regularly patched, meaning it\'s both useless and a potential risk.'},
  {id:2022,domain:'threats',q:'What type of malware is used to gather information about a user\'s browsing habits and system?',choices:['Spyware','A Trojan','Bloatware','A rootkit'],exp:'Spyware is specifically designed to gather information about users and systems and to send that data back to a central collector.'},
  {id:2023,domain:'threats',q:'Matt uploads a malware sample to a third-party malware scanning site that uses multiple antimalware and antivirus engines to scan the sample. He receives multiple different answers for what the malware package is. What has occurred?',choices:['Different vendors use different names for malware packages.','The package contains more than one piece of malware.','The service is misconfigured.','The malware is polymorphic and changed while being tested.'],exp:'One of the challenges security practitioners can face when attempting to identify malware is that different antivirus and antimalware vendors will name malware packages and families differently. This means that Matt may need to look at different names to figure out what he is dealing with.'},
  {id:2024,domain:'threats',q:'Nancy is concerned that there is a software keylogger on the system she\'s investigating. What best describes data that may have been stolen?',choices:['Keyboard and other input from the user','All files on the system','All keyboard input','All files the user accessed while the keylogger was active'],exp:'While keyloggers often focus on keyboard input, other types of input may also be captured, meaning Nancy should worry about any user input that occurred while the keylogger was installed. Keyloggers typically do not target files on systems, although if Nancy finds a keylogger, she may want to check for other malware packages with additional capabilities.'},
  {id:2025,domain:'threats',q:'A system in Elaine\'s company has suddenly displayed a message demanding payment in Bitcoin and claiming that the data from the system has been encrypted. What type of malware has Elaine likely encountered?',choices:['Ransomware','Worms','A virus','Rootkit'],exp:'Ransomware demands payment to be made while typically using encryption to make data inaccessible.'},
  {id:2026,domain:'threats',q:'Rick believes that a system he is responsible for has been compromised with malware that uses a rootkit to obtain and retain access to the system. When he runs an antimalware tool\'s scanner, the system doesn\'t show any malware. If he has other data that indicates the system is infected, what should his next step be if he wants to determine what malware may be on the system?',choices:['Mount the drive on another system and scan it that way.','Rerun the antimalware scan.','Disable the system\'s antivirus because it may be causing a false negative.','The system is not infected and he should move on.'],exp:'Rootkits are designed to hide from antimalware scanners and can often defeat locally run scans. Mounting the drive in another system in read-only mode or booting from a USB drive and scanning using a trusted, known good operating system can be an effective way to determine what malware is on a potentially infected system.'},
  {id:2027,domain:'threats',q:'A recently terminated developer from Jaya\'s organization has contacted the organization claiming that they left code in an application that they wrote that will delete files and bring the application down if they are not employed by the company. What type of malware is this?',choices:['A logic bomb','Ransomware','Extortionware','A Trojan'],exp:'Jaya\'s former employee is describing a logic bomb, malicious code that will cause harm when a trigger or specific action occurs. In this case, the former employee is claiming that the trigger is them not being employed at the company. Jaya will need to assess all of the code that the employee wrote to determine if a logic bomb exists.'},
  {id:2028,domain:'threats',q:'Selah wants to ensure that malware is completely removed from a system. What should she do to ensure this?',choices:['Wipe the drive and restore from known good media.','Run multiple antimalware tools and use them to remove all detections.','Use the delete setting in her antimalware software rather than the quarantine setting.','There is no way to ensure the system is safe and it should be destroyed.'],exp:'In most malware infection scenarios, wiping the drive and reinstalling from known good media is the best option available. If the malware has tools that can infect the system BIOS/UEFI, even this may not be sufficient, but BIOS/UEFI resident malware is relatively uncommon.'},
  {id:2029,domain:'threats',q:'What is the key difference between a worm and a virus?',choices:['How they spread','What operating system they run on','What their potential impact is','The number of infections'],exp:'The key difference between worms and viruses is how they spread. Worms spread themselves, whereas viruses rely on human interaction.'},
  {id:2030,domain:'threats',q:'Ben wants to analyze Python code that he believes may be malicious code written by an employee of his organization. What can he do to determine if the code is malicious?',choices:['Open the file using a text editor to review the code','Run a decompiler against it to allow him to read the code','Test the code using an antivirus tool','Submit the Python code to a malware testing website'],exp:'Python is an interpreted rather than a compiled language, so Ben doesn\'t need to use a decompiler. Instead, his best bet is to open the file and review the code to see what it does. Since it was written by an employee, it is unlikely that it will match an existing known malicious package, which means antivirus and antimalware tools and sites will be useless.'},
  {id:2031,domain:'threats',q:'Which of the following defenses is most likely to prevent Trojan installation?',choices:['Preventing downloads from application stores','Installing patches for known vulnerabilities','Preventing the use of USB drives','Disabling autorun from USB drives'],exp:'Trojans are often found in application stores where they appear to be innocuous but desirable applications or are listed in confusingly similar ways to legitimate applications. Many organizations choose to lock down the ability to acquire applications from app stores to prevent this type of issue.'},
  {id:2032,domain:'threats',q:'Jason\'s security team reports that a recent WordPress vulnerability seems to have been exploited by malware and that their organization\'s entire WordPress service cluster has been infected. What type of malware is most likely involved if a vulnerability in the software was exploited over the network?',choices:['A worm','A logic bomb','A Trojan','A rootkit'],exp:'Worms often spread via networks, taking advantage of vulnerabilities to install themselves on targeted systems and then to propagate further.'},
  {id:2033,domain:'threats',q:'Hui\'s organization recently purchased new Windows computers from an office supply store. The systems have a number of unwanted programs on them that load at startup which were installed by the manufacturer. What type of software is this?',choices:['Bloatware','Viruses','Trojans','Spyware'],exp:'Unwanted, typically preinstalled programs are known as bloatware. They take up space and resources without providing value, and many organizations either uninstall them or install clean operating system images to avoid them.'},
  {id:2034,domain:'threats',q:'What type of malware connects to a command and control system, allowing attackers to manage, control, and update it remotely?',choices:['A bot','A drone','A vampire','A worm'],exp:'Bots connect to command and control (C&C) systems, allowing them to be updated, controlled, and managed remotely.'},
  {id:2035,domain:'threats',q:'Randy believes that a system that he is responsible for was infected after a user picked up a USB drive and plugged it in. The user claims that they only opened one file on the drive to see who might own it. What type of malware is most likely involved?',choices:['A virus','A worm','A Trojan','A spyware tool'],exp:'Randy knows that viruses spread through user interaction with files on thumb drives.'},
  {id:2036,domain:'threats',q:'Gary is reviewing his system\'s SSH logs and sees logins for the user named "Gary" with passwords like password1, password2, and PassworD. What type of attack has Gary discovered?',choices:['A dictionary attack','A rainbow table attack','A pass-the-hash attack','A password spraying attack'],exp:'A dictionary attack will use a set of likely passwords along with common variants of those passwords to try to break into an account. Repeated logins for a single user ID with iterations of various passwords is likely a dictionary attack.'},
  {id:2037,domain:'threats',q:'Joseph receives an email notifying him that he needs to change his password due to a recent account issue. He notices that the email links him to a website using the domain amaz0n.com. What type of attack should he describe this as?',choices:['Phishing','Typosquatting','Smishing','A watering hole attack'],exp:'The email is an attempt to get account information and is a phishing email. Joseph did not enter the URL himself, which is the behavior a typosquatter relies on.'},
  {id:2038,domain:'threats',q:'When you combine phishing with voicemail, it is known as:',choices:['Vishing','Whaling','Spoofing','Spooning'],exp:'Vishing is a form of phishing done via voice phone calls or voicemail.'},
  {id:2039,domain:'threats',q:'While reviewing her logs, Michele notices that a remote system has attempted to log into her server via SSH using the username admin and a variety of passwords like "password" and "ninja." What type of attack has Michele noticed?',choices:['A brute-force attack','Shoulder surfing','An on-path attack','Pretexting'],exp:'Michele has discovered a brute-force attack, which relies on trying a large number of passwords, often combined with a list of usernames to try.'},
  {id:2040,domain:'threats',q:'Joanna wants to detect password spraying attacks. What type of rule should she deploy through her security systems?',choices:['Match repeated use of the same password during failed login attempts for multiple usernames.','Match attempts to log into many systems with the same username and password.','Match multiple attempts to log into the same user account using different passwords.','Match all attempts to use passwords with slight changes for the same account.'],exp:'Password spraying involves the use of the same password to attempt to log into multiple accounts. Joanna should search for uses of the same password for different accounts.'},
  {id:2041,domain:'threats',q:'One of the staff at Susan\'s organization has reported that a critical vendor has contacted them about an unpaid invoice. After Susan investigates, she discovers that the invoice was sent from an email account that was not typically a contact and that the invoice requested payment to a PayPal account. What type of social engineering attack has Susan most likely discovered?',choices:['Business email compromise','Smishing','Disinformation','Typosquatting'],exp:'Susan has most likely discovered a business email compromise and should reach out to the impacted organization to inform them of the potentially compromised account.'},
  {id:2042,domain:'threats',q:'Selah infects the ads on a website that users from her target company frequently visit with malware as part of her penetration test. What technique has she used?',choices:['A watering hole attack','Vishing','Whaling','Typosquatting'],exp:'Watering hole attacks rely on compromising or infecting a website that targeted users frequently visit, much like animals will visit a common watering hole.'},
  {id:2043,domain:'threats',q:'Ben wants to determine if brute-force password attacks are being used against his company. What log information is LEAST likely to be useful when working to detect brute-force attacks?',choices:['The geographic location of system being logged into','Source IP address or hostname','Failed login logs','The password that was used for each attempt'],exp:'The source IP or hostname; the failed login logs with time, date, username, and other information; and the password that was used for each failed attempt would be useful for watching for brute-force attempts. Knowing where the system being logged into is located isn\'t useful when tracking brute-force attempts.'},
  {id:2044,domain:'threats',q:'Melissa receives a call and the caller informs her a senior manager in her organization needs her to buy gift cards for an event that starts in an hour. The caller says that the senior leader forgot to get the cards, and that the event is critical to her organization. Melissa buys the cards and sends them to the Gmail address the caller says that the senior leader needs them sent to. What type of attack has Melissa fallen for?',choices:['Pretexting','Phishing','Business email compromise','Carding'],exp:'The caller is using pretexting, providing Melissa with a story that relies on urgency and perceived authority to get her to take actions she might normally question.'},
  {id:2045,domain:'threats',q:'Alaina wants to determine if a password spraying attack was used against her organization. Which of the following indicators would be most useful as part of her investigation?',choices:['The passwords used for failed attempts','The time the login attempts happened','The source IP address of the attempts','The number of failed attempts for each user'],exp:'Password spraying attempts try to use a single common password for many user accounts. Determining if a single password is being used over and over can help catch basic password spraying attempts.'},
  {id:2046,domain:'threats',q:'Which of the following human vectors is primarily associated with nation-state actors?',choices:['Misinformation campaigns','Watering hole attacks','Business email compromise','Password spraying'],exp:'Misinformation and disinformation campaigns are primarily associated with nation-state actors, but are increasingly used by other organizations and even individuals as well.'},
  {id:2047,domain:'threats',q:'Nicole accidentally types www.smazon.com into her browser and discovers that she is directed to a different site loaded with ads and pop-ups. Which of the following is the most accurate description of the attack she has experienced?',choices:['Typosquatting','DNS hijacking','Pharming','Hosts file compromise'],exp:'Typosquatting uses misspellings and common typos of websites to redirect traffic for profit or malicious reasons. Fortunately in reality, if you visit smazon.com, you\'ll be redirected to the actual amazon.com website, as Amazon knows about and works to prevent this type of issue.'},
  {id:2048,domain:'threats',q:'Devon is a penetration tester and sets up malicious tools on his target organization\'s primary internal website. What type of attack is he conducting?',choices:['A watering hole attack','A misinformation campaign','A typosquatting attack','A disinformation campaign'],exp:'Devon is conducting a watering hole attack that leverages a frequently visited site to deploy malware.'},
  {id:2049,domain:'threats',q:'Phishing emails sent pretending to be from a company that recipients are familiar with and likely to respond to is what type of attack?',choices:['Brand impersonation','Phishing','Pharming','Pretexting'],exp:'Brand impersonation attacks are designed to appear to be from a company that recipients are likely to be familiar with, and thus are more likely to elicit a response. While these are a type of phishing, the more specific answer of brand impersonation is the best answer.'},
  {id:2050,domain:'threats',q:'When a caller was recently directed to Amanda, who is a junior IT employee at her company, the caller informed her that they were the head of IT for her organization and that she needed to immediately disable the organization\'s firewall. After Amanda made the change, she discovered that the caller was actually a penetration tester hired by her company. What social engineering attack best describes this?',choices:['Impersonation','Smishing','Pretexting','Vishing'],exp:'This is an example of an impersonation attack. The pentester impersonated the head of IT in order to achieve their goals. The good news is that it was a penetration tester!'},
  {id:2051,domain:'threats',q:'Fred is concerned about text message-based attacks. Which of the following attacks relies on text messages as its primary focus?',choices:['Smishing','Impersonation','Watering hole attacks','Business email compromise'],exp:'Smishing is a type of phishing that occurs via text (SMS) messages.'},
  {id:2052,domain:'threats',q:'Sharif notices that his authentication logs have many different usernames showing failed logins with the same password. What type of attack has he discovered?',choices:['Spraying','Credential harvesting','Impersonation','BEC'],exp:'Sharif has discovered a spraying attack that uses the same password — often a default or common password — with many usernames.'},
  {id:2053,domain:'threats',q:'Naomi receives a report of smishing. What type of attack should she be looking for?',choices:['Text message-based phishing','Compressed files in phishing','Voicemail-based phishing','Server-based phishing'],exp:'Smishing is a type of phishing that occurs via text (SMS) messages.'},
  {id:2054,domain:'threats',q:'Jack\'s organization wants to prevent typosquatting. What option should he select to address this issue?',choices:['Purchase the most common typos for his organization\'s domain','Copyright the domain name','Trademark the domain name','Disable typo resolution for the domain'],exp:'While it\'s nearly impossible to prevent typosquatting, purchasing and registering the most common typos (typo-domains) related to your organization\'s domain and redirecting them to your real domain is the most effective option available.'},
  {id:2055,domain:'threats',q:'Gwyne\'s company has been contacted by customers asking about a new social media account operating under the company\'s brand. The social media account is advertising cryptocurrency, which Gwyne\'s organization does not sell or work with. What type of attack best describes what Gwyne\'s organization has encountered?',choices:['Brand impersonation','Impersonation','Mis-branding','Crypto-phishing'],exp:'Using an organization\'s brand in this way is an example of brand impersonation. While this is also an impersonation attack, the more specific description is the best answer here.'},
  {id:2056,domain:'threats',q:'Nation-state-driven social media campaigns about the trustworthiness of the U.S. election in 2016 are an example of what type of social engineering?',choices:['Disinformation','Smishing','Pretexting','Spraying'],exp:'Disinformation campaigns are used to shift public opinion or to accomplish other goals. They are not limited to nation-state actors but are an increasingly heavily used social engineering tactic at a broad scale.'},
  {id:2057,domain:'threats',q:'Charles is worried about users conducting SQL injection attacks. Which of the following solutions will best address his concerns?',choices:['Performing user input validation','Using secure session management','Enabling logging on the database','Implementing TLS'],exp:'Charles should perform user input validation to strip out any SQL code or other unwanted input.'},

  // ── DOMAIN 3: SECURITY ARCHITECTURE ──
  // ── STUDY GUIDE ──
  {id:3001,domain:'architecture',q:'Greg is implementing a data loss prevention system. He would like to ensure that it protects against transmissions of sensitive information by guests on his wireless network. What DLP technology would best meet this goal?',choices:['Network-based','Watermarking','Pattern recognition','Host-based'],exp:'In this case, Greg must use a network-based DLP system. Host-based DLP requires the use of agents, which would not be installed on guest systems.'},
  {id:3002,domain:'architecture',q:'What term best describes data that is being sent between two systems over a network connection?',choices:['Data in transit','Data at rest','Data in processing','Data in use'],exp:'Data being sent over a network is data in transit.'},
  {id:3003,domain:'architecture',q:'Stephanie is reviewing a customer transaction database that has credit card number information that looks like these: c4ca4238a0b923820dcc509a6f75849b, c81e728d9d4c2f636f067f89cc14862c, eccbc87e4b5ce2fe28308fd9f2a7baf3. What data minimization technique has most likely been used to obscure the credit card information in this table?',choices:['Hashing','Destruction','Masking','Tokenization'],exp:'This data most closely resembles hashed data, as the fields are all the same length and appear to contain meaningless but unique data. If the field was tokenized, it would be more likely to contain a sequential number or other recognizable identifier. If the field was masked, it would contain asterisks or other placeholder characters.'},
  {id:3004,domain:'architecture',q:'Tara recently analyzed the results of a vulnerability scan report and found that a vulnerability reported by the scanner did not exist because the system was actually patched as specified. What type of error occurred?',choices:['False positive','False negative','True positive','True negative'],exp:'A false positive error occurs when the vulnerability scanner reports a vulnerability that does not actually exist.'},
  // ── PRACTICE TESTS ──
  {id:3005,domain:'architecture',q:'Nancy wants to adopt a backup strategy that will meet her organization\'s desires about the amount of data that could be lost in a scenario where a restoration from backup was required and also wants to establish guidelines for how long a restoration should take. What two key objectives should she set?',choices:['An RPO and an RTO','An RFBT and an RPO','An RPO and a MTBF','A MTBF and an RFBT'],exp:'Organizations set recovery point objectives (RPOs), which describe how much data is acceptable to lose in a data loss event, and recovery time objectives (RTOs), which describe the maximum amount of time that it should take to recover data. Together these two objectives help guide backup strategy and infrastructure design and implementation.'},

  // ── DOMAIN 4: SECURITY OPERATIONS ──
  // ── STUDY GUIDE ──
  {id:4001,domain:'operations',q:'Which of the following measures is NOT commonly used to assess threat intelligence?',choices:['Detail','Timeliness','Accuracy','Relevance'],exp:'Although higher levels of detail can be useful, they aren\'t a common a measure used to assess threat intelligence. Instead, the timeliness, accuracy, and relevance of the information are considered critical to determining whether you should use the threat information.'},
  {id:4002,domain:'operations',q:'Which organization did the U.S. government help create to share knowledge between organizations in specific verticals?',choices:['ISACs','DHS','SANS','CERTS'],exp:'The U.S. government created the Information Sharing and Analysis Centers (ISACs). ISACs help infrastructure owners and operators share threat information, and provide tools and assistance to their members.'},
  {id:4003,domain:'operations',q:'Ken is conducting threat research on Transport Layer Security (TLS) and would like to consult the authoritative reference for the protocol\'s technical specification. What resource would best meet his needs?',choices:['Internet RFCs','Academic journal','Subject matter experts','Textbooks'],exp:'All of these resources might contain information about the technical details of TLS, but Internet Request for Comments (RFC) documents are the definitive technical standards for Internet protocols. Consulting the RFCs would be Ken\'s best option.'},
  {id:4004,domain:'operations',q:'Which one of the following threat research tools is used to visually display information about the location of threat actors?',choices:['Threat map','Predictive analysis','Vulnerability feed','STIX'],exp:'Threat maps are graphical tools that display information about the geographic locations of attackers and their targets. These tools are most often used as interesting marketing gimmicks, but they can also help identify possible threat sources.'},
  {id:4005,domain:'operations',q:'Which one of the following information sources would NOT be considered an OSINT source?',choices:['Port scans','DNS lookup','Search engine research','WHOIS queries'],exp:'Port scans are an active reconnaissance technique that probe target systems and would not be considered open source intelligence (OSINT).'},
  {id:4006,domain:'operations',q:'Renee is configuring her vulnerability management solution to perform credentialed scans of servers on her network. What type of account should she provide to the scanner?',choices:['Read-only','Domain administrator','Local administrator','Root'],exp:'Credentialed scans only require read-only access to target servers. Renee should follow the principle of least privilege and limit the access available to the scanner.'},
  {id:4007,domain:'operations',q:'Ryan is planning to conduct a vulnerability scan of a business critical system using dangerous plug-ins. What would be the best approach for the initial scan?',choices:['Run the scan in a test environment.','Run the scan against production systems to achieve the most realistic results possible.','Run the scan during business hours.','Do not run the scan to avoid disrupting the business.'],exp:'Ryan should first run his scan against a test environment to identify likely vulnerabilities and assess whether the scan itself might disrupt business activities.'},
  {id:4008,domain:'operations',q:'Which one of the following values for the CVSS attack complexity metric would indicate that the specified attack is simplest to exploit?',choices:['Low','High','Medium','Severe'],exp:'An attack complexity of "low" indicates that exploiting the vulnerability does not require any specialized conditions.'},
  {id:4009,domain:'operations',q:'Brian ran a penetration test against a school\'s grading system and discovered a flaw that would allow students to alter their grades by exploiting a SQL injection vulnerability. What type of control should he recommend to the school\'s cybersecurity team to prevent students from engaging in this type of activity?',choices:['Integrity','Confidentiality','Alteration','Availability'],exp:'By allowing students to change their own grades, this vulnerability provides a pathway to unauthorized alteration of information. Brian should recommend that the school deploy integrity controls that prevent unauthorized modifications.'},
  {id:4010,domain:'operations',q:'Which one of the following security assessment tools is LEAST likely to be used during the reconnaissance phase of a penetration test?',choices:['Metasploit','Nmap','Nessus','Nslookup'],exp:'Nmap is a port scanning tool used to enumerate open network ports on a system. Nessus is a vulnerability scanner designed to detect security issues on a system. Nslookup is a DNS information gathering utility. All three of these tools may be used to gather information and detect vulnerabilities. Metasploit is an exploitation framework used to execute and attack and would be better suited for the Attacking and Exploiting phase of a penetration test.'},
  {id:4011,domain:'operations',q:'During a penetration test, Patrick deploys a toolkit on a compromised system and uses it to gain access to other systems on the same network. What term best describes this activity?',choices:['Lateral movement','Privilege escalation','Footprinting','OSINT'],exp:'Moving from one compromised system to other systems on the same network is known as lateral movement.'},
  {id:4012,domain:'operations',q:'Kyle is conducting a penetration test. After gaining access to an organization\'s database server, he installs a backdoor on the server to grant himself access in the future. What term best describes this action?',choices:['Persistence','Privilege escalation','Lateral movement','Maneuver'],exp:'Backdoors are a persistence tool, designed to make sure that the attacker\'s access persists after the original vulnerability is remediated. Kyle can use this backdoor to gain access to the system in the future, even if the original exploit that he used to gain access is no longer effective.'},
  {id:4013,domain:'operations',q:'Which element of the SCAP framework can be used to consistently describe vulnerabilities?',choices:['CVE','CPE','CVSS','CCE'],exp:'Common Vulnerabilities and Exposures (CVE) provides a standard nomenclature for describing security-related software flaws.'},
  {id:4014,domain:'operations',q:'Grace would like to determine the operating system running on a system that she is targeting in a penetration test. Which one of the following techniques will most directly provide her with this information?',choices:['Footprinting','Port scanning','Vulnerability scanning','Packet capture'],exp:'All of these techniques might provide Grace with information about the operating system running on a device. However, footprinting is a technique specifically designed to elicit this information.'},
  {id:4015,domain:'operations',q:'Kevin recently identified a new security vulnerability and computed its CVSS base score as 6.5. Which risk category would this vulnerability fall into?',choices:['Medium','Low','High','Critical'],exp:'Vulnerabilities with CVSS base scores between 4.0 and 6.9 fit into the medium risk category. Vulnerability scores between 0.1 and 3.9 would be low, between 7.0 and 8.9 would be high, and those between 9.0 and 10.0 would be in the critical risk category.'},
  {id:4016,domain:'operations',q:'Which one of the CVSS metrics would contain information about the type of account access that an attacker must have to execute an attack?',choices:['PR','AV','C','AC'],exp:'The privileges required (PR) metric indicates the type of system access that an attacker must have to execute the attack.'},
  {id:4017,domain:'operations',q:'Adam is conducting software testing by reviewing the source code of the application. What type of code testing is Adam conducting?',choices:['Static code analysis','Mutation testing','Dynamic code analysis','Fuzzing'],exp:'Adam is conducting static code analysis by reviewing the source code.'},

  // ── DOMAIN 5: SECURITY PROGRAM MANAGEMENT & OVERSIGHT ──
  // ── STUDY GUIDE ──
  {id:5001,domain:'governance',q:'Jade\'s organization suffered a breach and her primary concern is sanctions for violating PCI DSS. What category of risk is this?',choices:['Compliance','Strategic','Reputational','Operational'],exp:'Jade\'s primary concern is violating a specific regulation (PCI DSS), making this a compliance risk.'},
  {id:5002,domain:'governance',q:'Tony is reviewing the status of his organization\'s defenses against a breach of their file server. He believes that a compromise of the file server could reveal information that would prevent the company from continuing to do business. What term best describes the risk that Tony is considering?',choices:['Strategic','Reputational','Financial','Operational'],exp:'The risk that Tony is contemplating could fit any one of these categories. However, his primary concern is that the company may no longer be able to do business if the risk materializes. This is a strategic risk.'},
  {id:5003,domain:'governance',q:'Which US regulation governs the protection of patient health information?',choices:['HIPAA','GDPR','PCI-DSS','SOX'],exp:'HIPAA (Health Insurance Portability and Accountability Act) protects patient health information. GDPR covers EU data; PCI-DSS covers payment cards.'},
  {id:5004,domain:'governance',q:'Which one of the following security assessment techniques assumes that an organization has already been compromised and searches for evidence of that compromise?',choices:['Threat hunting','Vulnerability scanning','Penetration testing','War driving'],exp:'Threat hunting is an assessment technique that makes an assumption of compromise and then searches the organization for indicators of compromise that confirm the assumption.'},
  {id:5005,domain:'governance',q:'Zian is a cybersecurity leader who is coordinating the activities of a security audit. The audit is being done to validate the organization\'s financial statements to investors and involves a review of cybersecurity controls. What term best describes this audit?',choices:['External audit','Penetration test','Internal audit','Informal audit'],exp:'Audits performed to validate an organization\'s financial statements are very formal audits that are performed by independent third-party auditors. This makes them external audits. Internal audits may be more or less formal than external audits, but they are generally done only to provide assurance to internal parties and not to investors.'},
  {id:5006,domain:'governance',q:'Which one of the following assessment techniques is designed to solicit participation from external security experts and reward them for discovering vulnerabilities?',choices:['Bug bounty','Threat hunting','Penetration testing','Vulnerability scanning'],exp:'Bug bounty programs are designed to allow external security experts to test systems and uncover previously unknown vulnerabilities. Bug bounty programs offer successful testers financial rewards to incentivize their participation.'},
  {id:5007,domain:'governance',q:'Which one of the following techniques would be considered passive reconnaissance?',choices:['WHOIS lookups','Port scans','Vulnerability scans','Footprinting'],exp:'WHOIS lookups use external registries and are an example of open source intelligence (OSINT), which is a passive reconnaissance technique.'},
  {id:5008,domain:'governance',q:'Bruce is conducting a penetration test for a client. The client provided him with full details of their systems in advance. What type of test is Bruce conducting?',choices:['Known environment test','Partially known environment test','Detailed environment test','Unknown environment test'],exp:'Known environment tests are performed with full knowledge of the underlying technology, configurations, and settings that make up the target.'},
  {id:5009,domain:'governance',q:'Lila is working on a penetration testing team, and she is unsure whether she is allowed to conduct social engineering as part of the test. What document should she consult to find this information?',choices:['Rules of engagement','Contract','Statement of work','Lessons learned report'],exp:'The rules of engagement provide technical details on the parameters of the test.'},
  {id:5010,domain:'governance',q:'Jean recently completed the user acceptance testing process and is getting her code ready to deploy. What environment should house her code before it is released for use?',choices:['Staging','Test','Production','Development'],exp:'The staging environment is a transition environment for code that has successfully cleared testing and is waiting to be deployed into production. This is where the code should reside before it is released for use.'},
];

// ════════════════════════════════════════════════
// FILL-IN-THE-BLANK QUESTIONS
// answer = correct word; bank[0] is always the correct answer, shuffled at runtime
// ════════════════════════════════════════════════
const FITB_QUESTIONS=[
  // ── DOMAIN 2: THREATS ──
  {id:2058,domain:'threats',type:'fitb',q:'A ___ attack intercepts communications between two parties without their knowledge.',answer:'man-in-the-middle',bank:['man-in-the-middle','replay','smurf','watering hole'],exp:'A man-in-the-middle attack positions the attacker between two communicating parties.'},
  {id:2059,domain:'threats',type:'fitb',q:'___ is malware that encrypts victim files and demands payment for the decryption key.',answer:'Ransomware',bank:['Ransomware','Rootkit','Spyware','Adware'],exp:'Ransomware encrypts files and holds them hostage until a ransom is paid.'},
  {id:2060,domain:'threats',type:'fitb',q:'A ___ attack registers a domain name spelled just one letter differently from a legitimate site.',answer:'typosquatting',bank:['typosquatting','watering hole','pharming','vishing'],exp:'Typosquatting exploits users who mistype a URL, redirecting them to a malicious site.'},
  {id:2061,domain:'threats',type:'fitb',q:'___ is the use of a fabricated scenario to trick a victim into revealing information.',answer:'Pretexting',bank:['Pretexting','Tailgating','Vishing','Smishing'],exp:'Pretexting creates a false (pretext) scenario to manipulate the victim into disclosing information.'},
  {id:2062,domain:'threats',type:'fitb',q:'Phishing attacks that specifically target senior executives are called ___.',answer:'whaling',bank:['whaling','spear phishing','vishing','smishing'],exp:'Whaling is phishing aimed specifically at high-value targets like C-suite executives.'},
  {id:2063,domain:'threats',type:'fitb',q:'___ is intelligence gathered from publicly available sources such as search engines and WHOIS records.',answer:'OSINT',bank:['OSINT','STIX','OPSEC','TAXII'],exp:'Open Source Intelligence (OSINT) is collected from publicly available sources without active probing.'},
  {id:2064,domain:'threats',type:'fitb',q:'Trying a small set of common passwords across many accounts to avoid lockouts is called password ___.',answer:'spraying',bank:['spraying','stuffing','cracking','forcing'],exp:'Password spraying avoids account lockouts by trying a few common passwords across many accounts rather than hammering one account.'},
  {id:2076,domain:'threats',type:'fitb',q:'A ___ is a collection of malware-infected computers controlled remotely by an attacker, often used for spam or DDoS attacks.',answer:'botnet',bank:['botnet','worm','RAT','rootkit'],exp:'A botnet (robot network) is a group of compromised hosts under centralized attacker control. Individual hosts are called bots or drones and communicate via a command-and-control (C&C) channel.'},
  // ── DOMAIN 1: GENERAL ──
  {id:1020,domain:'general',type:'fitb',q:'___ adds a unique random value to a password before hashing to defeat rainbow table attacks.',answer:'Salting',bank:['Salting','Stretching','Padding','Seeding'],exp:'A salt is a unique random value added to each password before hashing, making precomputed rainbow tables useless.'},
  {id:1021,domain:'general',type:'fitb',q:'___ encryption uses one key to encrypt and the same key to decrypt.',answer:'Symmetric',bank:['Symmetric','Asymmetric','Hashing','Elliptic'],exp:'Symmetric encryption uses a single shared secret key for both encryption and decryption.'},
  {id:1022,domain:'general',type:'fitb',q:'The ___ is the PKI component responsible for issuing and signing digital certificates.',answer:'Certificate Authority',bank:['Certificate Authority','Registration Authority','OCSP Responder','CRL'],exp:'The Certificate Authority (CA) issues and signs certificates. The Registration Authority verifies identity before the CA issues.'},
  {id:1029,domain:'general',type:'fitb',q:'The ___ triad represents the three core objectives of information security: Confidentiality, Integrity, and Availability.',answer:'CIA',bank:['CIA','DAD','AAA','GRC'],exp:'The CIA triad — Confidentiality, Integrity, and Availability — is the foundation of information security. Every security control is designed to protect one or more of these three objectives.'},
  {id:1030,domain:'general',type:'fitb',q:'A ___ control provides an alternative safeguard that satisfies the intent of a requirement when the primary control is not feasible.',answer:'compensating',bank:['compensating','corrective','deterrent','residual'],exp:'Compensating controls must meet the intent and rigor of the original requirement. Under PCI DSS, a control that fulfills one requirement cannot also serve as a compensating control for another.'},
  // ── DOMAIN 3: ARCHITECTURE ──
  {id:3006,domain:'architecture',type:'fitb',q:'The ___ principle states that users should only have the minimum access necessary to perform their job.',answer:'least privilege',bank:['least privilege','separation of duties','zero trust','need to know'],exp:'Least privilege limits access rights to the bare minimum, reducing attack surface and blast radius.'},
  {id:3007,domain:'architecture',type:'fitb',q:'A ___ is a decoy system designed to attract attackers and study their behavior.',answer:'honeypot',bank:['honeypot','DMZ','bastion host','proxy'],exp:'A honeypot is a decoy system that lures attackers, allowing defenders to observe their techniques.'},
  {id:3011,domain:'architecture',type:'fitb',q:'A ___ is a network segment positioned between the untrusted internet and the internal trusted network, typically hosting public-facing services.',answer:'DMZ',bank:['DMZ','VLAN','MPLS','subnet'],exp:'A DMZ (demilitarized zone) isolates public-facing servers — web, email, DNS — from the internal network. A compromised DMZ host still faces a second firewall before reaching internal systems.'},
  // ── DOMAIN 4: OPERATIONS ──
  {id:4018,domain:'operations',type:'fitb',q:'___ analysis examines malware code without executing it.',answer:'Static',bank:['Static','Dynamic','Heuristic','Behavioral'],exp:'Static analysis examines malware without running it. Dynamic analysis executes it in a controlled environment to observe behavior.'},
  {id:4019,domain:'operations',type:'fitb',q:'A ___ backup copies only data changed since the last full backup.',answer:'differential',bank:['differential','incremental','full','snapshot'],exp:'Differential backups copy everything changed since the last full backup. Incremental copies only what changed since the last backup of any type.'},
  {id:4026,domain:'operations',type:'fitb',q:'The ___ is a standardized scoring system that rates software vulnerability severity on a scale from 0 to 10.',answer:'CVSS',bank:['CVSS','CVE','CPE','CCE'],exp:'The Common Vulnerability Scoring System (CVSS) produces a 0–10 severity score using metrics like attack vector, complexity, privileges required, and impact on confidentiality, integrity, and availability.'},
  // ── DOMAIN 5: GOVERNANCE ──
  {id:5011,domain:'governance',type:'fitb',q:'A ___ assessment assigns monetary values to risk, such as Annual Loss Expectancy.',answer:'quantitative',bank:['quantitative','qualitative','residual','inherent'],exp:'Quantitative risk assessments express risk in numerical monetary terms. Qualitative assessments use categories like high/medium/low.'},
  {id:5012,domain:'governance',type:'fitb',q:'The ___ is the maximum acceptable time that systems can be down after an incident.',answer:'RTO',bank:['RTO','RPO','MTTR','MTBF'],exp:'Recovery Time Objective (RTO) defines the maximum acceptable downtime. RPO defines acceptable data loss measured in time.'},
  {id:5013,domain:'governance',type:'fitb',q:'___ testing begins with no prior knowledge of the target environment, simulating an external attacker.',answer:'Black-box',bank:['Black-box','White-box','Gray-box','Crystal-box'],exp:'Black-box testing simulates a real attacker with no insider knowledge. White-box gives the tester full information.'},
  {id:5014,domain:'governance',type:'fitb',q:'The ___ is a NIST framework that organizes cybersecurity around Identify, Protect, Detect, Respond, and Recover.',answer:'CSF',bank:['CSF','COBIT','ISO 27001','ITIL'],exp:'The NIST Cybersecurity Framework (CSF) provides a flexible, risk-based structure around five core functions.'},
  {id:5020,domain:'governance',type:'fitb',q:'___ is the EU regulation that governs how organizations collect, store, and process personal data belonging to EU citizens.',answer:'GDPR',bank:['GDPR','HIPAA','SOX','PCI DSS'],exp:'The General Data Protection Regulation (GDPR) grants EU citizens rights over their personal data and imposes strict handling requirements — with fines up to 4% of global annual revenue for serious violations.'},
];

// ════════════════════════════════════════════════
// MATCHING QUESTIONS
// pairs: [{left, right}] — right side is shuffled at runtime, left stays fixed
// ════════════════════════════════════════════════
const MATCH_QUESTIONS=[
  // ── DOMAIN 2: THREATS ──
  {id:2065,domain:'threats',type:'match',q:'Match each attack to its description.',pairs:[
    {left:'Phishing',right:'Deceptive email designed to steal credentials'},
    {left:'Vishing',right:'Voice call used to trick victims into revealing information'},
    {left:'Smishing',right:'SMS-based social engineering attack'},
    {left:'Whaling',right:'Phishing attack targeting senior executives'},
  ],exp:'These are all social engineering techniques, each delivered through a different channel.'},
  {id:2066,domain:'threats',type:'match',q:'Match each malware type to its defining behavior.',pairs:[
    {left:'Ransomware',right:'Encrypts files and demands payment'},
    {left:'Rootkit',right:'Hides itself by modifying the operating system'},
    {left:'Keylogger',right:'Captures keystrokes to steal credentials'},
    {left:'Logic bomb',right:'Lies dormant until a trigger condition is met'},
  ],exp:'Each malware type has a distinct mechanism and purpose that makes it identifiable.'},
  {id:2067,domain:'threats',type:'match',q:'Match each threat actor to their most common motivation.',pairs:[
    {left:'Nation-state actor',right:'Espionage and geopolitical disruption'},
    {left:'Hacktivist',right:'Political or philosophical beliefs'},
    {left:'Organized crime',right:'Financial gain'},
    {left:'Insider threat',right:'Blackmail, revenge, or financial gain'},
  ],exp:'Threat actor motivations help defenders predict likely targets and attack methods.'},
  {id:2077,domain:'threats',type:'match',q:'Match each malware type to how it spreads or is activated.',pairs:[
    {left:'Virus',right:'Spreads by attaching to files; requires user interaction to execute'},
    {left:'Worm',right:'Self-replicates across networks without any user interaction'},
    {left:'Trojan',right:'Disguises itself as legitimate software; user installs it willingly'},
    {left:'Logic bomb',right:'Remains dormant until a specific trigger condition is met'},
  ],exp:'Propagation method is the key distinguisher between these malware types. Worms are self-propagating; viruses need a human to execute the infected file; Trojans rely on deception; logic bombs wait for a trigger.'},
  // ── DOMAIN 1: GENERAL ──
  {id:1023,domain:'general',type:'match',q:'Match each encryption type to its key characteristic.',pairs:[
    {left:'Symmetric',right:'Same key for encryption and decryption'},
    {left:'Asymmetric',right:'Uses a public/private key pair'},
    {left:'Hashing',right:'One-way transformation — cannot be reversed'},
    {left:'Salting',right:'Random value added before hashing to prevent rainbow tables'},
  ],exp:'Understanding how these cryptographic concepts differ is essential for Security+.'},
  {id:1024,domain:'general',type:'match',q:'Match each protocol to its default port.',pairs:[
    {left:'HTTPS',right:'443'},
    {left:'SSH',right:'22'},
    {left:'HTTP',right:'80'},
    {left:'RDP',right:'3389'},
  ],exp:'Memorizing common port numbers is a reliable point-earner on the Security+ exam.'},
  {id:1031,domain:'general',type:'match',q:'Match each control category to how it is implemented.',pairs:[
    {left:'Technical',right:'Enforced through software, hardware, or firmware (firewalls, encryption, ACLs)'},
    {left:'Managerial',right:'Addressed through policies, procedures, and risk management processes'},
    {left:'Physical',right:'Implemented with tangible measures such as locks, cameras, and barriers'},
    {left:'Operational',right:'Carried out by people through training, security awareness, and day-to-day tasks'},
  ],exp:'Control categories describe HOW a control works. Technical controls are automated; managerial controls are administrative; physical controls are tangible; operational controls are people-driven.'},
  // ── DOMAIN 3: ARCHITECTURE ──
  {id:3008,domain:'architecture',type:'match',q:'Match each cloud model to what it provides.',pairs:[
    {left:'IaaS',right:'Virtualized hardware — servers, storage, networking'},
    {left:'PaaS',right:'Platform for developers to build and deploy apps'},
    {left:'SaaS',right:'Ready-to-use software delivered over the internet'},
    {left:'FaaS',right:'Event-driven code execution without managing servers'},
  ],exp:'The key difference is how much of the stack the customer manages vs. the provider.'},
  // ── DOMAIN 5: GOVERNANCE ──
  {id:5015,domain:'governance',type:'match',q:'Match each control type to its purpose.',pairs:[
    {left:'Preventive',right:'Stops an incident before it occurs'},
    {left:'Detective',right:'Identifies and alerts on incidents in progress'},
    {left:'Corrective',right:'Restores systems after an incident has occurred'},
    {left:'Deterrent',right:'Discourages attackers from attempting an attack'},
  ],exp:'Security controls are categorized by when and how they act relative to an incident.'},
  {id:5021,domain:'governance',type:'match',q:'Match each regulation to the type of data or industry it primarily governs.',pairs:[
    {left:'HIPAA',right:'Patient health information in the United States'},
    {left:'GDPR',right:'Personal data of EU citizens across all industries'},
    {left:'PCI DSS',right:'Credit and debit cardholder payment data'},
    {left:'SOX',right:'Financial record accuracy for U.S. publicly traded companies'},
  ],exp:'These four regulations appear frequently on Security+. Each targets a specific sector: healthcare privacy (HIPAA), broad EU data rights (GDPR), payment cards (PCI DSS), and public company financial reporting (SOX).'},
  // ── DOMAIN 4: OPERATIONS ──
  {id:4020,domain:'operations',type:'match',q:'Match each backup type to its behavior.',pairs:[
    {left:'Full backup',right:'Copies all data regardless of what has changed'},
    {left:'Differential',right:'Copies all changes since the last full backup'},
    {left:'Incremental',right:'Copies only changes since the last backup of any type'},
    {left:'Snapshot',right:'Point-in-time image of a system or volume'},
  ],exp:'These backup types differ in speed, storage use, and recovery complexity.'},
  {id:4027,domain:'operations',type:'match',q:'Match each penetration testing phase to its description.',pairs:[
    {left:'Reconnaissance',right:'Gather information about the target before any active probing'},
    {left:'Scanning',right:'Probe systems for open ports, services, and potential vulnerabilities'},
    {left:'Gaining Access',right:'Exploit identified vulnerabilities to compromise a system'},
    {left:'Maintaining Access',right:'Install backdoors or persistence mechanisms for continued control'},
  ],exp:'Pen testing follows a structured lifecycle. Reconnaissance is largely passive; scanning is active; gaining access exploits findings; maintaining access ensures the tester can return — mimicking a real attacker\'s behavior.'},
];

// ════════════════════════════════════════════════
// SCENARIO SORTER QUESTIONS
// steps[0] is always the correct first step; steps are in correct order in source data
// ════════════════════════════════════════════════
const SORT_QUESTIONS=[
  // ── DOMAIN 4: OPERATIONS ──
  {id:4021,domain:'operations',type:'sort',q:'Arrange the incident response lifecycle phases in the correct order.',steps:['Preparation','Identification','Containment','Eradication','Recovery','Lessons Learned'],exp:'The standard IR lifecycle: Preparation → Identification → Containment → Eradication → Recovery → Lessons Learned.'},
  {id:4022,domain:'operations',type:'sort',q:'Arrange these penetration testing phases in the correct order.',steps:['Planning & Reconnaissance','Scanning','Gaining Access','Maintaining Access','Reporting'],exp:'Pen testing follows a structured lifecycle from scoping and recon through exploitation to final documentation.'},
  {id:4023,domain:'operations',type:'sort',q:'A malware infection has been detected on a workstation. Arrange the correct response steps in order.',steps:['Isolate the infected workstation from the network','Capture forensic evidence and document findings','Remove malware and patch the vulnerability','Restore from a known-good backup if needed','Return the system to production and monitor'],exp:'Containment comes first to prevent spread, then forensics before eradication to preserve evidence.'},
  // ── DOMAIN 5: GOVERNANCE ──
  {id:5016,domain:'governance',type:'sort',q:'Arrange these risk management steps in the correct order.',steps:['Identify assets','Identify threats and vulnerabilities','Assess likelihood and impact','Select and implement controls','Monitor and review'],exp:'Risk management is a continuous cycle starting with understanding what you\'re protecting.'},
  {id:5017,domain:'governance',type:'sort',q:'Arrange these vulnerability management steps in the correct order.',steps:['Discover and inventory assets','Scan assets for vulnerabilities','Prioritize vulnerabilities by risk','Remediate or mitigate findings','Verify remediation and rescan'],exp:'Vulnerability management is a cycle — you must know what you have before you can scan it, and verify fixes before closing findings.'},
  {id:5022,domain:'governance',type:'sort',q:'Arrange the SDLC environments in the order that code typically passes through them.',steps:['Development','Testing','Staging','Production'],exp:'Code moves from Development (written and unit-tested) → Testing (QA/integration) → Staging (pre-production validation mirror) → Production (live environment). Staging is the final safety net before real users see the code.'},
  // ── DOMAIN 1: GENERAL ──
  {id:1025,domain:'general',type:'sort',q:'Arrange the steps of a TLS handshake in the correct order.',steps:['Client sends ClientHello with supported cipher suites','Server responds with ServerHello and its certificate','Client verifies certificate and sends key exchange','Server and client derive session keys','Encrypted communication begins'],exp:'The TLS handshake negotiates parameters and establishes shared session keys before any application data flows.'},
  // ── DOMAIN 2: THREATS ──
  {id:2078,domain:'threats',type:'sort',q:'Arrange the stages of a typical phishing attack in the correct order.',steps:['Research the target to craft a convincing lure','Send the malicious email to the target','Target clicks a link or opens an attachment','Capture credentials or install malware','Use access for data theft or further compromise'],exp:'Phishing follows an attacker kill chain: reconnaissance → delivery → exploitation → collection → action on objectives. Defending at each stage — email filters, user training, EDR, MFA — reduces the attack\'s success rate.'},
];

// ════════════════════════════════════════════════
// TRUE / FALSE WITH A TWIST
// correct: true|false  wrongParts: shown only when answer is false
// ════════════════════════════════════════════════
const TF_QUESTIONS=[
  // ── DOMAIN 2: THREATS ──
  {id:2068,domain:'threats',type:'tf',q:'A watering hole attack works by sending malicious emails directly to targeted employees.',correct:false,wrongParts:['It targets employees directly','It uses email as the vector','It compromises websites the targets frequently visit','It involves phone calls'],wrongAnswer:2,exp:'Watering hole attacks compromise websites the target group frequently visits — they wait for victims to come to them, rather than reaching out directly.'},
  {id:2069,domain:'threats',type:'tf',q:'Smishing attacks are delivered via voice phone calls.',correct:false,wrongParts:['Smishing uses voice phone calls','Smishing uses SMS text messages','Smishing uses social media messages','Smishing uses email'],wrongAnswer:1,exp:'Smishing uses SMS (text messages). Vishing uses voice calls. Both are social engineering variants.'},
  {id:2070,domain:'threats',type:'tf',q:'Nation-state actors are most commonly motivated by financial gain.',correct:false,wrongParts:['They are motivated by financial gain','They are motivated by espionage and geopolitical goals','They are motivated by political beliefs','They are motivated by revenge'],wrongAnswer:1,exp:'Nation-state actors are primarily motivated by espionage, intelligence gathering, disruption, and geopolitical advantage. Financial gain is more associated with organized crime.'},
  {id:2079,domain:'threats',type:'tf',q:'A rootkit is designed to make its presence obvious so that administrators can quickly detect the compromise.',correct:false,wrongParts:['Rootkits generate alerts visible in standard system logs','Rootkits are specifically designed to HIDE by modifying the OS or firmware','Rootkits announce themselves after achieving persistence','Rootkits are installed through visible software packages'],wrongAnswer:1,exp:'Rootkits are engineered to conceal themselves — they modify the operating system, kernel, or firmware to hide files, processes, and network connections from both administrators and security tools.'},
  // ── DOMAIN 1: GENERAL ──
  {id:1026,domain:'general',type:'tf',q:'WPA3 uses Simultaneous Authentication of Equals (SAE) to replace the vulnerable WPA2 four-way handshake.',correct:true,exp:'WPA3\'s SAE handshake is resistant to offline dictionary attacks and replaces the WPA2 Pre-Shared Key handshake.'},
  {id:1027,domain:'general',type:'tf',q:'A digital signature uses the sender\'s private key to sign data, and the recipient uses the sender\'s public key to verify it.',correct:true,exp:'This is correct — the private key signs, the public key verifies. This proves both identity and integrity.'},
  {id:1028,domain:'general',type:'tf',q:'Symmetric encryption is generally faster than asymmetric encryption for bulk data.',correct:true,exp:'Symmetric encryption is much faster and is used for bulk data. Asymmetric encryption is slower and typically used only for key exchange or signatures.'},
  {id:1032,domain:'general',type:'tf',q:'A wildcard certificate issued for *.example.com will also secure the root domain example.com.',correct:false,wrongParts:['Wildcard certs secure only the root domain — not any subdomains','Wildcard certs cover subdomains (e.g. mail.example.com) but NOT the root domain itself','Wildcard certs cover all levels including sub-subdomains','Wildcard certs from the same CA automatically cover related domains'],wrongAnswer:1,exp:'A wildcard cert (*.example.com) covers exactly one level of subdomains but does NOT cover the bare root domain (example.com) or sub-subdomains (a.b.example.com). A separate certificate or SAN entry is needed for the root.'},
  // ── DOMAIN 5: GOVERNANCE ──
  {id:5018,domain:'governance',type:'tf',q:'A quantitative risk assessment expresses risk using categories like High, Medium, and Low.',correct:false,wrongParts:['Risk is expressed using categories like High/Medium/Low','Risk is expressed using monetary values and probabilities','Risk is expressed using color-coded matrices','Risk is expressed using letter grades'],wrongAnswer:1,exp:'Quantitative assessments use monetary values — like Annual Loss Expectancy. Qualitative assessments use categories like High, Medium, and Low.'},
  {id:5019,domain:'governance',type:'tf',q:'The NIST Cybersecurity Framework was developed by the Payment Card Industry to protect cardholder data.',correct:false,wrongParts:['It was developed by the Payment Card Industry','It was developed by NIST for general cybersecurity risk management','It was developed by HIPAA for healthcare','It was developed by the EU for data protection'],wrongAnswer:1,exp:'The NIST CSF was developed by the National Institute of Standards and Technology as a general-purpose cybersecurity framework. PCI-DSS protects cardholder data.'},
  {id:5023,domain:'governance',type:'tf',q:'HIPAA compliance applies only to hospitals and physicians — third-party vendors who process health data on their behalf are exempt.',correct:false,wrongParts:['HIPAA applies exclusively to government-funded healthcare programs','HIPAA also applies to business associates who create, receive, or transmit PHI on behalf of covered entities','HIPAA applies to any organization in the U.S. that collects any personal data','HIPAA compliance is optional for vendors with fewer than 50 employees'],wrongAnswer:1,exp:'HIPAA applies to covered entities (providers, insurers, clearinghouses) AND their business associates — any organization that handles Protected Health Information on behalf of a covered entity must also comply.'},
  // ── DOMAIN 3: ARCHITECTURE ──
  {id:3009,domain:'architecture',type:'tf',q:'In a Zero Trust architecture, users on the internal network are implicitly trusted without requiring authentication.',correct:false,wrongParts:['Internal users are implicitly trusted','All users must verify regardless of network location','Only external users require authentication','Trust is granted after first login'],wrongAnswer:1,exp:'Zero Trust means "never trust, always verify" — no user or device is implicitly trusted, even on the internal network.'},
  {id:3010,domain:'architecture',type:'tf',q:'An air-gapped system can still communicate with external networks using encrypted VPN tunnels.',correct:false,wrongParts:['It can use encrypted VPN tunnels to communicate externally','It is physically isolated with no network connections to external systems','It uses one-way data diodes for communication','It requires physical media for data transfer'],wrongAnswer:1,exp:'An air gap means physical isolation — no network connections to external systems at all, encrypted or otherwise.'},
  {id:3012,domain:'architecture',type:'tf',q:'Given the correct key, a hash value can be reversed to recover the original plaintext.',correct:false,wrongParts:['Hashing is reversible by any party who knows the algorithm used','Hashing is a one-way function — there is no key and the output cannot be reversed','Only older algorithms like MD5 can be reversed with sufficient computing power','Hash values can be reversed using the same algorithm in decryption mode'],wrongAnswer:1,exp:'Hashing is a one-way function — unlike encryption, there is no key and the original data cannot be mathematically recovered from the hash. This is what makes hashes suitable for password storage.'},
  // ── DOMAIN 4: OPERATIONS ──
  {id:4024,domain:'operations',type:'tf',q:'A false positive in vulnerability scanning occurs when the scanner reports a vulnerability that does not actually exist.',correct:true,exp:'A false positive is a reported vulnerability that does not actually exist. A false negative is a real vulnerability that the scanner misses.'},
  {id:4025,domain:'operations',type:'tf',q:'In incident response, eradication should be performed before containment.',correct:false,wrongParts:['Eradication comes before containment','Containment comes before eradication','Both happen simultaneously','Order does not matter'],wrongAnswer:1,exp:'Containment must come first to prevent the incident from spreading. Only after containment is it safe to eradicate the threat.'},
  {id:4028,domain:'operations',type:'tf',q:'Port scanning is considered passive reconnaissance because it does not require making connections to the target system.',correct:false,wrongParts:['Port scanning is passive because it only collects publicly available information','Port scanning is active reconnaissance — it sends packets to the target and analyzes responses','Port scanning is passive when performed on behalf of an authorized client','Port scanning is only considered active if it modifies data on the target'],wrongAnswer:1,exp:'Port scanning is active reconnaissance — it directly probes the target by sending packets and observing responses, making it detectable by IDS. Passive recon (OSINT, WHOIS) gathers information without touching the target.'},
];

// ════════════════════════════════════════════════
// PHISHING / SPOT THE VULNERABILITY
// redFlags[0] is always the primary red flag (shuffled at runtime)
// ════════════════════════════════════════════════
const PHISH_QUESTIONS=[
  {id:2071,domain:'threats',type:'phish',
    email:{from:'security-alert@paypa1.com',to:'brandon.hayes@company.com',subject:'URGENT: Your account has been limited',body:`Dear Valued Customer,

We have detected unusual activity on your PayPal account. Your account has been temporarily limited until you confirm your information.

Please click the link below immediately to restore access:

http://paypa1-secure.account-verify.net/restore

Failure to verify within 24 hours will result in permanent account suspension.

— The PayPal Security Team`},
    redFlags:['The sender domain uses "paypa1" with a number instead of the letter "l"','The email uses urgent language and a 24-hour deadline to pressure action','The link goes to account-verify.net, not paypal.com','The greeting says "Valued Customer" rather than your actual name'],
    correct:0,
    exp:'The most reliable red flag here is the typosquatted sender domain — paypa1.com uses the number 1 instead of the letter l. Always check the sender domain carefully before clicking anything.'},
  {id:2072,domain:'threats',type:'phish',
    email:{from:'it-support@company-helpdesk.net',to:'all-staff@company.com',subject:'Action Required: Password Reset',body:`Hi Team,

Our IT systems are undergoing maintenance tonight. All employees must reset their passwords before 5 PM today to avoid being locked out.

Please use the following link to reset your password:

http://company-helpdesk.net/reset?token=a8f3k2

Enter your current password first to verify your identity, then create a new one.

Thank you,
IT Support`},
    redFlags:['Legitimate password reset flows never ask for your current password first','The sender domain company-helpdesk.net is not the company\'s official domain','The email creates urgency with a same-day deadline','IT maintenance windows rarely require all-staff password resets'],
    correct:0,
    exp:'Asking for your current password to "verify identity" before resetting it is credential harvesting — legitimate reset flows never work this way. This is the clearest technical red flag in the email.'},
  {id:2073,domain:'threats',type:'phish',
    email:{from:'ceo.michael.rowe@company.com',to:'sarah.finance@company.com',subject:'Wire Transfer — Confidential',body:`Sarah,

I need you to process an urgent wire transfer of $47,500 to a new vendor. This is time-sensitive and must be completed today before end of business.

Please keep this between us for now — I'll explain everything on Monday. Do not discuss with anyone else in the office.

Account:
Bank: First National
Routing: 021000021
Account: 8834921047

Thanks,
Michael`},
    redFlags:['The request demands secrecy — "keep this between us" — before the action is taken','Wire transfer requests should always go through standard approval channels','The urgency and "I\'ll explain later" framing are classic BEC manipulation tactics','The dollar amount ($47,500) is just below common approval thresholds'],
    correct:0,
    exp:'The secrecy demand is the most distinctive BEC indicator — legitimate executives don\'t ask staff to hide financial transactions. Always verify large wire transfers through a separate, known-good communication channel.'},
  {id:2074,domain:'threats',type:'phish',
    email:{from:'no-reply@netflix-billing.co',to:'user@email.com',subject:'Your payment method failed — update now',body:`Hello,

We were unable to process your last Netflix payment. Your account will be suspended in 48 hours unless you update your billing information.

Update your payment method here:
https://netflix-billing.co/update-payment

We accept all major credit cards.

Netflix Billing Department`},
    redFlags:['The sender and link domain is netflix-billing.co — not netflix.com','The email uses a generic "Hello" greeting instead of your account name','The 48-hour suspension threat is designed to create panic and bypass critical thinking','Netflix billing emails always come from @netflix.com addresses'],
    correct:0,
    exp:'The off-brand domain (netflix-billing.co vs netflix.com) is the clearest red flag — Netflix\'s actual emails always come from @netflix.com. When in doubt, go directly to the website rather than clicking any link in the email.'},
  {id:2075,domain:'threats',type:'phish',
    email:{from:'awards@microsoft-survey.com',to:'you@youremail.com',subject:'You\'ve been selected for a $500 Microsoft Gift Card!',body:`Congratulations!

You have been randomly selected to receive a $500 Microsoft Gift Card as part of our annual customer satisfaction survey.

To claim your reward, complete the 2-minute survey below:

http://microsoft-survey.com/claim?id=GC500-USER

Note: You must provide your Microsoft account credentials to verify eligibility. Your card will be delivered within 3-5 business days.

Microsoft Rewards Team`},
    redFlags:['Legitimate Microsoft surveys never ask for your account credentials to claim a reward','The sender domain is microsoft-survey.com, not microsoft.com','Unsolicited prize offers are a classic social engineering lure','The email arrived unsolicited with no prior relationship established'],
    correct:0,
    exp:'No legitimate company will ever ask for your account credentials to verify eligibility for a prize. Credential harvesting disguised as a reward claim is a textbook phishing technique.'},
  {id:2080,domain:'threats',type:'phish',
    email:{from:'itsecurity@helpdesk-corp.net',to:'james.whitmore@company.com',subject:'IT Security Alert — Account Compromised',body:`Hi James,

Our security monitoring systems have detected that your account credentials may have been exposed in a recent data breach.

To secure your account immediately, please verify your identity at the link below:

http://helpdesk-corp.net/secure-verify?user=james.whitmore

You must complete this within 1 hour or your account will be locked pending a manual security review.

— IT Security Team
Incident Reference: SEC-20847`},
    redFlags:['The sender domain helpdesk-corp.net is not the company\'s own domain','Legitimate IT security teams never ask employees to log in through an unrecognized external link','The 1-hour deadline is engineered to create panic and prevent careful evaluation','Real incident notifications go through internal ticketing systems and involve your manager'],
    correct:0,
    exp:'The off-brand sender domain is the primary red flag — your company\'s IT team communicates from company-owned domains, not external services. Any "verify your account" request via an external link should be confirmed through a known-good channel before acting.'},
];

const ALL_Q = [...QUESTIONS, ...FITB_QUESTIONS, ...MATCH_QUESTIONS, ...SORT_QUESTIONS, ...TF_QUESTIONS, ...PHISH_QUESTIONS];
